### ISSUE TITLE
Question: why U60 instead of U64 ?

### ISSUE THREAD

**Issue by tinybeachthor** [HigherOrderCO/Kindex#114]
Is there a technical reason for not using sizes multiple of 8?

**Comment by developedby** [comment]
Kind is basically a thin typed layer on top of the HVM, which uses 60 bit integers for better performance (due to it's internal memory layout). And so, Kind inherited U60 numbers and there wasn't really any particular reason to also implement U64 numbers.

**Comment by tinybeachthor** [comment]
Got it thanks! So it's just for these memory tags https://github.com/HigherOrderCO/HVM/blob/05a69844fc100b9df9f60ed0c86a15cb209981ef/src/runtime/base/memory.rs#L226
